# Generated by Django 5.2.16 on 2026-07-30 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_id', models.CharField(max_length=100)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('vaccine_code', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('dosage_amount', models.CharField(max_length=100)),
                ('vaccination_age', models.CharField(max_length=100)),
                ('min_age', models.CharField(max_length=100)),
                ('max_age', models.CharField(max_length=100)),
                ('emergency_vaccine', models.CharField(max_length=100)),
                ('side_effects', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hospital_type', models.CharField(max_length=100)),
                ('ownership_model', models.CharField(max_length=100)),
                ('established_date', models.DateField()),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100)),
                ('hospital_logo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('AUTH_USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_time', models.DateField()),
                ('to_time', models.DateField()),
                ('slot_no', models.CharField(max_length=100)),
                ('HOSPITAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hospital')),
                ('VACCINAION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vaccination')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('gender', models.DateField()),
                ('photo', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('AUTH_USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.DateField()),
                ('SLOT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.slot')),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantinty_available', models.CharField(max_length=100)),
                ('HOSPITAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hospital')),
                ('VACCINATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vaccination')),
            ],
        ),
        migrations.CreateModel(
            name='CountryVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('VACCINATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vaccination')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('HOSPITAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hospital')),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
    ]
