# Generated by Django 5.2.16 on 2026-08-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='from_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='to_time',
            field=models.TimeField(),
        ),
    ]
