# Generated by Django 5.2.16 on 2026-08-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_slot_from_time_alter_slot_to_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='VACCINAION',
            new_name='VACCINATION',
        ),
    ]
