# Generated by Django 5.2.16 on 2026-08-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_booking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantinty_available',
            new_name='quantity_available',
        ),
    ]
