# Generated by Django 5.2.16 on 2026-08-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_quantinty_available_stock_quantity_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='slot_no',
            new_name='no_of_slots',
        ),
    ]
