# Generated by Django 5.2.16 on 2026-08-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_slot_no_slot_no_of_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slot_no',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
