# Generated by Django 5.2.16 on 2026-08-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_booking_slot_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='USERS',
        ),
        migrations.AddField(
            model_name='booking',
            name='For_Id',
            field=models.IntegerField(default='not assigned'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.CharField(default='not assigned', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot_no',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
