# Generated by Django 5.2.16 on 2026-08-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_booking_users_booking_for_id_booking_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='For_Id',
            new_name='for_id',
        ),
    ]
