# Generated by Django 5.2.16 on 2026-08-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_booking_for_id_remove_booking_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='USERS',
        ),
        migrations.AddField(
            model_name='booking',
            name='for_id',
            field=models.IntegerField(default='not assigned'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.CharField(default='not assigned', max_length=50),
            preserve_default=False,
        ),
    ]
