# Generated by Django 5.2.16 on 2026-08-06 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_booking_users_booking_for_id_booking_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='for_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='type',
        ),
        migrations.AddField(
            model_name='booking',
            name='USERS',
            field=models.ForeignKey(default='not assigned', on_delete=django.db.models.deletion.CASCADE, to='myapp.users'),
            preserve_default=False,
        ),
    ]
