# Generated by Django 5.2.16 on 2026-08-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_booking_for_id_remove_booking_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='typee',
            field=models.CharField(default='not assigned', max_length=50),
            preserve_default=False,
        ),
    ]
