# Generated by Django 5.2.16 on 2026-08-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_booking_typee'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='forid',
            field=models.IntegerField(default=0),
        ),
    ]
