# Generated by Django 5.2.16 on 2026-08-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_booking_forid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='no_of_slots',
            field=models.IntegerField(default=0),
        ),
    ]
