# Generated by Django 5.2.16 on 2026-08-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_slot_no_of_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinedocument',
            name='time',
            field=models.TimeField(),
        ),
    ]
