# Generated by Django 5.2.16 on 2026-08-11 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_vaccinedocument_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinedocument',
            name='VACCINATION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.vaccination'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccinedocument',
            name='forid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vaccinedocument',
            name='typee',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
