# Generated by Django 5.2.16 on 2026-08-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_vaccinedocument_vaccination_vaccinedocument_forid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinedocument',
            name='VACCINATION',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.vaccination'),
        ),
        migrations.AlterField(
            model_name='vaccinedocument',
            name='typee',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
